apiVersion: networking.k8s.io/v1
kind: Ingress # Permite criarmos um ingress para acessarmos nosso serviço de maneira externa ao cluster K8S
metadata:
  name: wordpress-ingress # Nome da configuração de Ingress
spec:
  rules:
  - host: wordpress-service.com
  - http: 
      paths:
      - path: / # Permite acesso a todos os recursos/páginas do nosso serviço (/qualquer/caminho/possivel)
        pathType: Prefix # Indica que o path indicado acima, trata-se de um prefixo da URL requisitada
        backend:
          service:
            name: wordpress-service # Nome do service que será direcionada a requisição
            port:
              number: 80 # Porta do service que será direcionada a requisição

--- 
#Os parametros abaixo são necessários, pois no Killercode roda em HTTPS mesmo na porta 80, então precisamos de enviar um header para o container em todas as requests
#conforme a documentação: https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy
# referencia: https://medium.com/@_jonas/traefik-kubernetes-ingress-and-x-forwarded-headers-82194d319b0e
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--entryPoints.web.proxyProtocol.insecure"
      - "--entryPoints.web.forwardedHeaders.insecure"
