apiVersion: v1
kind: PersistentVolumeClaim # Permite criarmos volumes persistentes para nossos containers
metadata:
  name: wordpress-data-pvc # Nome da configuração de PVC
  labels:
    app: wordpress-data # Label aplicada no PVC criado, contendo o nome da aplicação
spec:
  accessModes:
    - ReadWriteOnce # Permite que único container acesse o mesmo volume persistente
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi # Limita o armazenamento em disco do volume em 1GB